### ISSUE TITLE
DescribeAlign Hangs-Errors on CTRL+C

### ISSUE THREAD

**Issue by y0himba** [julbean/describealign#13]
Hello.  My wife is blind and we use Plex for most of our media. This would be a Godsend for someone like me who is not tech savvy. I have tried both ways to install both using PIP and then cloning the repository. 

When using pip, DescribeAlign hangs and produces the same errors after a bit.  When using the cloned repository I need to keyboard interrupt with `CTRL+C` to end it from being hung.  No GUI appears. 

I think I may need to create a venv with the proper Python version, but have no idea how to. 

If anyone can help, it would be much appreciated. 

Windows 11 242H
Python 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]

When using git clone:

```
PS C:\Tools\describealign> python .\describealign.py
Traceback (most recent call last):
  File "C:\Python313\Lib\tempfile.py", line 257, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\Python313\\Lib\\site-packages\\librosa\\util\\__pycache__\\tmp2ytadt3a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Tools\describealign\describealign.py", line 73, in <module>
    import pytsmod
  File "C:\Python313\Lib\site-packages\pytsmod\__init__.py", line 5, in <module>
    from .hptsm import *
  File "C:\Python313\Lib\site-packages\pytsmod\hptsm.py", line 1, in <module>
    from librosa.effects import hpss
  File "C:\Python313\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Python313\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Python313\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Python313\Lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\librosa\util\utils.py", line 1847, in <module>
    @numba.jit(nopython=True, cache=True)
     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\numba\core\decorators.py", line 225, in wrapper
    disp.enable_caching()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\site-packages\numba\core\dispatcher.py", line 807, in enable_caching
    self._cache = FunctionCache(self.py_func)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\numba\core\caching.py", line 647, in __init__
    self._impl = self._impl_class(py_func)
                 ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Python313\Lib\site-packages\numba\core\caching.py", line 379, in __init__
    locator = cls.from_function(py_func, source_path)
  File "C:\Python313\Lib\site-packages\numba\core\caching.py", line 182, in from_function
    self.ensure_cache_path()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Python313\Lib\site-packages\numba\core\caching.py", line 109, in ensure_cache_path
    tempfile.TemporaryFile(dir=path).close()
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Python313\Lib\tempfile.py", line 583, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
                    newline=newline, encoding=encoding, errors=errors,
                    opener=opener)
  File "C:\Python313\Lib\tempfile.py", line 580, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\tempfile.py", line 263, in _mkstemp_inner
    if (_os.name == 'nt' and _os.path.isdir(dir) and
                             ~~~~~~~~~~~~~~^^^^^
KeyboardInterrupt
```

When using PIP install: 

```
C:\Windows\System32>describealign
C:\Python313\Lib\site-packages\librosa\util\files.py:10: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\describealign.exe\__main__.py", line 2, in <module>
    from describealign import command_line_interface
  File "C:\Python313\Lib\site-packages\describealign.py", line 71, in <module>
    import pytsmod
  File "C:\Python313\Lib\site-packages\pytsmod\__init__.py", line 5, in <module>
    from .hptsm import *
  File "C:\Python313\Lib\site-packages\pytsmod\hptsm.py", line 1, in <module>
    from librosa.effects import hpss
  File "C:\Python313\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Python313\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\librosa\core\constantq.py", line 1059, in <module>
    dtype=np.complex,
          ^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\numpy\__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
```

**Comment by julbean** [comment]
Apologies for the broken code!  Unfortunately it's currently nonfunctional for Python 3.13 and up, as one of the dependencies for this project, pytsmod, hasn't been updated in a few years.  I asked them to update it 5 months ago (https://github.com/KAIST-MACLab/PyTSMod/issues/23) but it looks like they aren't working on the project anymore.  The good news is that I'm currently working on describealign v2.0, which will remove pytsmod as a dependency.  It should be available in a few weeks once I've finished testing it.
The even better news is that you have a few options for getting describealign working right now!

1. Download the binary
2. Downgrade Python to 3.12 or lower
3. Install the stable dev branch version of describealign from two months ago which has pytsmod removed with these commands:
pip uninstall describealign
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ describealign==2.0.0b9

Let me know how it goes!

**Comment by y0himba** [comment]
WORKED.  I didn't downgrade Python, but the GUI is now running. The only error was:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
m4b-util 2025.4.16 requires natsort~=8.2.0, but you have natsort 8.4.0 which is incompatible.
```

**Comment by julbean** [comment]
Glad it works!
And for anyone reading this in the future, the list I posted above are not steps, but three different ways to get it working
